#!/bin/bash
set -e; set -o pipefail

# See https://stackoverflow.com/a/246128
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
"$script_dir"/kern-config

cd "$script_dir"/../linux
# See http://stackoverflow.com/a/6481016
cores=$(grep -c ^processor /proc/cpuinfo)
make -j $((cores+1)) $@
